# Generated by Django 4.2 on 2023-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAR', '0002_image_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
