# Generated by Django 4.2 on 2023-07-19 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebAR", "0003_alter_image_image_alter_image_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(
                upload_to="uploads/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(["gltf", "glb"])
                ],
            ),
        ),
    ]
