# Generated by Django 4.2 on 2023-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebAR", "0005_image_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="size",
            field=models.FloatField(default=1.0),
        ),
    ]
